# -*- coding: utf-8 -*-
"""SQL procurement chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RRFIxytuTdok_OXBqmkUt8Z5vXf0RZds
"""

!pip install -q transformers accelerate gradio plotly pandas tabulate
# (transformers + accelerate load and run Qwen on the GPU)

from google.colab import files
import os
if not os.path.exists("maritime.db"):
    print("Please upload maritime.db")
    uploaded = files.upload()
print("DB files here:", [f for f in os.listdir() if f.endswith('.db')])

# First run downloads ~15GB of weights; takes a few minutes. It caches
# for the session. If you hit out-of-memory, use the 3B model instead
# (see MODEL_NAME comment).
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

MODEL_NAME = "Qwen/Qwen2.5-7B-Instruct"
# Lighter fallback if the 7B OOMs on a small GPU:
# MODEL_NAME = "Qwen/Qwen2.5-3B-Instruct"

print(f"Loading {MODEL_NAME} ...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype="auto",     # bf16/fp16 on GPU
    device_map="auto",      # place on the GPU automatically
)
print("Model loaded on:", next(model.parameters()).device)


def qwen_chat(prompt: str, max_new_tokens: int = 500) -> str:
    """Single-turn helper: send a user prompt, get the text reply."""
    messages = [
        {"role": "system", "content": "You are a precise data assistant."},
        {"role": "user", "content": prompt},
    ]
    text = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = tokenizer([text], return_tensors="pt").to(model.device)
    out = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,        # deterministic -> stabler SQL
        temperature=None, top_p=None, top_k=None,
        pad_token_id=tokenizer.eos_token_id,
    )
    # keep only the newly generated tokens
    gen = out[0][inputs.input_ids.shape[1]:]
    return tokenizer.decode(gen, skip_special_tokens=True).strip()

import sqlite3, re
import pandas as pd
import plotly.express as px

DB_PATH = "maritime.db"

SCHEMA = """
You are querying a SQLite database about maritime crew wages and vessel insurance
for an oil-tanker fleet. Tables and columns:

vessels(vessel_id PK, vessel_name, imo_number, vessel_type, flag_state, dwt, year_built)
  - vessel_type is one of: Aframax, Suezmax, VLCC, MR, LR2 ; dwt = deadweight tonnes

crew(crew_id PK, full_name, nationality, rank, dept, date_joined)
  - dept is one of: Deck, Engine, Catering

crew_wages(wage_id PK, crew_id FK->crew, vessel_id FK->vessels, pay_month 'YYYY-MM',
           base_wage_usd, overtime_usd, leave_pay_usd, allowances_usd, total_wage_usd)
  - monthly USD; total_wage_usd = base + overtime + leave + allowances

insurance_policies(policy_id PK, vessel_id FK->vessels, cover_type, insurer, policy_year,
                   insured_value_usd, annual_premium_usd, deductible_usd)
  - cover_type is one of: H&M, P&I, War Risk, Loss of Hire
  - annual_premium_usd = yearly cost

insurance_claims(claim_id PK, policy_id FK->insurance_policies, claim_date, cover_type,
                 incident, claim_amount_usd, settled_amount_usd, status)
  - status is one of: Open, Settled, Denied

Join keys:
  crew_wages.crew_id = crew.crew_id
  crew_wages.vessel_id = vessels.vessel_id
  insurance_policies.vessel_id = vessels.vessel_id
  insurance_claims.policy_id = insurance_policies.policy_id

Conventions: "wages"->total_wage_usd ; "insurance cost"->annual_premium_usd ;
"settlement ratio"->SUM(settled_amount_usd)/SUM(claim_amount_usd).
"""

EXAMPLES = """
Q: What is the average total monthly wage for each rank?
SQL: SELECT c.rank, ROUND(AVG(w.total_wage_usd),2) AS avg_total_wage
     FROM crew_wages w JOIN crew c ON c.crew_id=w.crew_id
     GROUP BY c.rank ORDER BY avg_total_wage DESC;

Q: Which vessel type costs the most to insure per year?
SQL: SELECT v.vessel_type, ROUND(SUM(p.annual_premium_usd),2) AS total_premium
     FROM insurance_policies p JOIN vessels v ON v.vessel_id=p.vessel_id
     GROUP BY v.vessel_type ORDER BY total_premium DESC;

Q: What is the claims settlement ratio by cover type?
SQL: SELECT cover_type,
       ROUND(SUM(settled_amount_usd)/NULLIF(SUM(claim_amount_usd),0),3) AS settlement_ratio
     FROM insurance_claims GROUP BY cover_type ORDER BY settlement_ratio DESC;
"""


def generate_sql(question: str) -> str:
    """STAGE 1: question -> SQL (SELECT only) using Qwen."""
    prompt = f"""{SCHEMA}

Example question/SQL pairs:
{EXAMPLES}

Rules:
- Return ONLY one valid SQLite SELECT statement. No prose, no markdown fences.
- Read-only: never INSERT/UPDATE/DELETE/DROP/ALTER.
- Use explicit JOINs with the keys above. Round money to 2 dp, alias clearly.

Question: {question}
SQL:"""
    raw = qwen_chat(prompt, max_new_tokens=400)
    # strip fences and any trailing prose after the first statement
    raw = re.sub(r"```(?:sql)?", "", raw).replace("```", "").strip()
    # keep from first SELECT to the first semicolon (or end)
    m = re.search(r"(select\b.*?)(;|$)", raw, flags=re.IGNORECASE | re.DOTALL)
    return (m.group(1).strip() if m else raw)


def is_safe_select(sql: str) -> bool:
    s = sql.strip().rstrip(";").lower()
    if not s.startswith("select"):
        return False
    banned = ["insert", "update", "delete", "drop", "alter",
              "create", "attach", "pragma", ";"]
    return not any(b in s for b in banned)


def run_sql(sql: str) -> pd.DataFrame:
    con = sqlite3.connect(DB_PATH)
    try:
        return pd.read_sql_query(sql, con)
    finally:
        con.close()


def explain_result(question: str, sql: str, df: pd.DataFrame) -> str:
    """STAGE 3: results -> plain-English answer using Qwen."""
    preview = df.head(20).to_markdown(index=False)
    prompt = f"""User asked: "{question}"
SQL run:
{sql}
Result (first rows):
{preview}

Write a short, direct plain-English answer. Lead with the key number or finding.
2 to 4 sentences. Do not use em dashes or semicolons."""
    return qwen_chat(prompt, max_new_tokens=300)


def auto_chart(df: pd.DataFrame):
    if df.empty or df.shape[1] < 2:
        return None
    num_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
    cat_cols = [c for c in df.columns if c not in num_cols]
    if not cat_cols and len(num_cols) >= 2:
        cat_cols = [num_cols[0]]; num_cols = num_cols[1:]
    if not cat_cols or not num_cols:
        return None
    x, y = cat_cols[0], num_cols[0]
    d = df.head(25)
    try:
        fig = px.bar(d, x=x, y=y, title=f"{y} by {x}")
        fig.update_layout(xaxis_tickangle=-40, height=460)
        return fig
    except Exception:
        return None


def ask(question: str):
    if not question or not question.strip():
        return "Type a question about crew wages or insurance.", "", pd.DataFrame(), None
    try:
        sql = generate_sql(question)
    except Exception as e:
        return f"Could not generate SQL: {e}", "", pd.DataFrame(), None
    if not is_safe_select(sql):
        return ("For safety I only run read-only SELECT queries, and this did not "
                "produce one. Try rephrasing."), sql, pd.DataFrame(), None
    try:
        df = run_sql(sql)
    except Exception as e:
        return f"SQL failed to run: {e}", sql, pd.DataFrame(), None
    if df.empty:
        return "The query ran but returned no rows.", sql, df, None
    try:
        answer = explain_result(question, sql, df)
    except Exception as e:
        answer = f"(Could not summarise: {e})"
    return answer, sql, df, auto_chart(df)


# quick self-test
_a, _s, _d, _f = ask("average total monthly wage by rank")
print("SQL:\n", _s, "\n\nANSWER:\n", _a)
_d.head()

import gradio as gr

EXAMPLE_QS = [
    "Average total monthly wage by rank",
    "Which vessel type costs the most to insure per year?",
    "Claims settlement ratio by cover type",
    "Total overtime pay by department",
    "Which insurer has the most open claims?",
    "How many crew of each nationality are there?",
]

def ui_ask(question):
    answer, sql, df, fig = ask(question)
    sql_md = f"```sql\n{sql}\n```" if sql else ""
    return answer, sql_md, (df if not df.empty else pd.DataFrame()), fig

with gr.Blocks(title="Maritime Analytics Chatbot (Qwen)") as demo:
    gr.Markdown("## Maritime Analytics Chatbot SQL\n"
                "Ask about crew wages or vessel insurance in plain English. "
                "Qwen writes the SQL, runs it, explains the result, and charts it.")
    with gr.Row():
        q = gr.Textbox(label="Your question", scale=4,
                       placeholder="e.g. average total wage by rank")
        btn = gr.Button("Ask", variant="primary", scale=1)
    answer = gr.Markdown(label="Answer")
    with gr.Accordion("Generated SQL", open=False):
        sql_out = gr.Markdown()
    plot = gr.Plot(label="Chart")
    table = gr.Dataframe(label="Result table", wrap=True)

    gr.Examples(EXAMPLE_QS, inputs=q)
    btn.click(ui_ask, inputs=q, outputs=[answer, sql_out, table, plot])
    q.submit(ui_ask, inputs=q, outputs=[answer, sql_out, table, plot])

demo.launch(share=True)