# -*- coding: utf-8 -*-
"""SQL Upgraded Procurement Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkciwLSP4gXbgG-nFBR9Jz7h5XpxKemG
"""

!pip install -q transformers accelerate gradio plotly pandas tabulate

from google.colab import files
import os

# Upload ANY .db (SQLite) file here. Default name expected below is your file's name.
uploaded_names = []
existing = [f for f in os.listdir() if f.endswith(".db")]
if not existing:
    print("Please upload a SQLite .db file")
    up = files.upload()
    uploaded_names = list(up.keys())
    existing = [f for f in os.listdir() if f.endswith(".db")]

print("DB files available:", existing)
# Pick the first .db found (or set DB_PATH manually if you have several)
DB_PATH = existing[0]
print("Using database:", DB_PATH)

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

MODEL_NAME = "Qwen/Qwen2.5-7B-Instruct"
# If you hit CUDA out of memory on a free T4, use the smaller model:
# MODEL_NAME = "Qwen/Qwen2.5-3B-Instruct"

print(f"Loading {MODEL_NAME} ...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME, torch_dtype="auto", device_map="auto",
)
print("Model loaded on:", next(model.parameters()).device)


def qwen_chat(prompt: str, max_new_tokens: int = 500) -> str:
    messages = [
        {"role": "system", "content": "You are a precise data assistant."},
        {"role": "user", "content": prompt},
    ]
    text = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = tokenizer([text], return_tensors="pt").to(model.device)
    out = model.generate(
        **inputs, max_new_tokens=max_new_tokens, do_sample=False,
        temperature=None, top_p=None, top_k=None,
        pad_token_id=tokenizer.eos_token_id,
    )
    gen = out[0][inputs.input_ids.shape[1]:]
    return tokenizer.decode(gen, skip_special_tokens=True).strip()

import sqlite3, re
import pandas as pd
import plotly.express as px


def introspect_schema(db_path: str):
    """Read the database's own structure so the bot works on ANY SQLite file.
    Returns (schema_text, list_of_tables)."""
    con = sqlite3.connect(db_path)
    cur = con.cursor()
    tables = [r[0] for r in cur.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%'").fetchall()]
    lines, fks = [], []
    for t in tables:
        cols = cur.execute(f"PRAGMA table_info({t})").fetchall()
        coldesc = ", ".join(f"{c[1]} {c[2]}" for c in cols)
        lines.append(f"{t}({coldesc})")
        for fk in cur.execute(f"PRAGMA foreign_key_list({t})").fetchall():
            fks.append(f"{t}.{fk[3]} = {fk[2]}.{fk[4]}")
    con.close()
    schema = "Tables and columns:\n" + "\n".join(lines)
    if fks:
        schema += "\n\nForeign keys (use these to join):\n" + "\n".join(fks)
    return schema, tables


# Build the schema automatically from whatever DB was uploaded.
SCHEMA, TABLES = introspect_schema(DB_PATH)
print("Auto-detected schema:\n")
print(SCHEMA)

# Optional few-shot examples. These are generic and help query style.
# You can leave this empty ("") for a brand-new database, or paste in a few
# Q/SQL pairs specific to your data to improve accuracy.
EXAMPLES = """
Q: Show the count of rows grouped by a category column.
SQL: SELECT some_category, COUNT(*) AS n FROM some_table GROUP BY some_category ORDER BY n DESC;

Q: Show a numeric total grouped by a category, joined across two tables.
SQL: SELECT b.category, ROUND(SUM(a.amount),2) AS total
     FROM table_a a JOIN table_b b ON b.id = a.b_id
     GROUP BY b.category ORDER BY total DESC;
"""


def generate_sql(question: str) -> str:
    """STAGE 1: question -> SQL (SELECT only)."""
    prompt = f"""You write SQLite SQL for the database described below.

{SCHEMA}

Example query patterns (adapt to the real tables above, do not copy names literally):
{EXAMPLES}

Rules:
- Return ONLY one valid SQLite SELECT statement. No prose, no markdown fences.
- Read-only: never INSERT/UPDATE/DELETE/DROP/ALTER.
- Use only tables and columns that exist in the schema above.
- Use explicit JOINs on the listed keys. Round money-like numbers to 2 dp and alias columns clearly.

Question: {question}
SQL:"""
    raw = qwen_chat(prompt, max_new_tokens=400)
    raw = re.sub(r"```(?:sql)?", "", raw).replace("```", "").strip()
    m = re.search(r"(select\b.*?)(;|$)", raw, flags=re.IGNORECASE | re.DOTALL)
    return (m.group(1).strip() if m else raw)


def is_safe_select(sql: str) -> bool:
    s = sql.strip().rstrip(";").lower()
    if not s.startswith("select"):
        return False
    banned = ["insert", "update", "delete", "drop", "alter",
              "create", "attach", "pragma", ";"]
    return not any(b in s for b in banned)


def run_sql(sql: str) -> pd.DataFrame:
    con = sqlite3.connect(DB_PATH)
    try:
        return pd.read_sql_query(sql, con)
    finally:
        con.close()


def explain_result(question: str, sql: str, df: pd.DataFrame) -> str:
    """STAGE 3: results -> plain-English answer."""
    preview = df.head(20).to_markdown(index=False)
    prompt = f"""User asked: "{question}"
SQL run:
{sql}
Result (first rows):
{preview}

Write a short, direct plain-English answer. Lead with the key number or finding.
2 to 4 sentences. Do not use em dashes or semicolons."""
    return qwen_chat(prompt, max_new_tokens=300)


def _looks_time(colname: str, sample_value) -> bool:
    """Decide if a column is time-like, so we can draw a line chart."""
    xl = str(colname).lower()
    if any(k in xl for k in ["month", "date", "year", "time",
                             "period", "day", "week", "quarter"]):
        return True
    # value pattern like 2026, 2026-05, or 2026-05-01
    if re.match(r"^\d{4}(-\d{2}){0,2}$", str(sample_value)):
        return True
    return False


def make_chart(df: pd.DataFrame):
    """Pick a chart: line for time-series x, bar otherwise."""
    if df.empty or df.shape[1] < 2:
        return None
    num_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
    cat_cols = [c for c in df.columns if c not in num_cols]
    if not cat_cols and len(num_cols) >= 2:
        cat_cols = [num_cols[0]]; num_cols = num_cols[1:]
    if not cat_cols or not num_cols:
        return None
    x, y = cat_cols[0], num_cols[0]
    d = df.copy()
    time_like = _looks_time(x, d[x].iloc[0])
    try:
        if time_like:
            d = d.sort_values(by=x)          # order the axis for a sensible line
            fig = px.line(d, x=x, y=y, markers=True, title=f"{y} over {x}")
        else:
            d = d.head(25)
            fig = px.bar(d, x=x, y=y, title=f"{y} by {x}")
        fig.update_layout(xaxis_tickangle=-40, height=460)
        return fig
    except Exception:
        return None


def ask(question: str):
    if not question or not question.strip():
        return "Type a question about your data.", "", pd.DataFrame(), None
    try:
        sql = generate_sql(question)
    except Exception as e:
        return f"Could not generate SQL: {e}", "", pd.DataFrame(), None
    if not is_safe_select(sql):
        return ("For safety I only run read-only SELECT queries, and this did not "
                "produce one. Try rephrasing."), sql, pd.DataFrame(), None
    try:
        df = run_sql(sql)
    except Exception as e:
        return f"SQL failed to run: {e}", sql, pd.DataFrame(), None
    if df.empty:
        return "The query ran but returned no rows.", sql, df, None
    try:
        answer = explain_result(question, sql, df)
    except Exception as e:
        answer = f"(Could not summarise: {e})"
    return answer, sql, df, make_chart(df)


# quick self-test
_a, _s, _d, _f = ask(f"count rows in {TABLES[0]}")
print("\nSELF-TEST SQL:\n", _s, "\n\nANSWER:\n", _a)
_d.head()

import gradio as gr

# Example prompts are generic now; edit to match your data if you like.
EXAMPLE_QS = [
    f"How many rows are in {TABLES[0]}",
    "Show totals grouped by a category",
    "What are the top values by count",
]

def ui_ask(question):
    answer, sql, df, fig = ask(question)
    sql_md = f"```sql\n{sql}\n```" if sql else ""
    return answer, sql_md, (df if not df.empty else pd.DataFrame()), fig

with gr.Blocks(title="NL-to-SQL Chatbot") as demo:
    gr.Markdown("## Natural-Language SQL Chatbot\n"
                "Ask questions about the uploaded database in plain English. "
                "The model writes the SQL, runs it, explains the result, and charts it. "
                "Line charts are used for time series, bars otherwise.")
    with gr.Row():
        q = gr.Textbox(label="Your question", scale=4,
                       placeholder="e.g. total amount by category over time")
        btn = gr.Button("Ask", variant="primary", scale=1)
    answer = gr.Markdown(label="Answer")
    with gr.Accordion("Generated SQL", open=False):
        sql_out = gr.Markdown()
    plot = gr.Plot(label="Chart")
    table = gr.Dataframe(label="Result table", wrap=True)

    gr.Examples(EXAMPLE_QS, inputs=q)
    btn.click(ui_ask, inputs=q, outputs=[answer, sql_out, table, plot])
    q.submit(ui_ask, inputs=q, outputs=[answer, sql_out, table, plot])

demo.launch(share=True)